.TH dpkg\-repack 1 "2016-02-29" 1.43 "dpkg suite"
.SH NAME
dpkg\-repack \- put an unpacked .deb file back together
.
.SH SYNOPSIS
\fBdpkg\-repack\fP [\fIoption\fP...] \fIpackage-name\fP...
.
.SH DESCRIPTION
.B dpkg\-repack
creates a .deb file out of a Debian package
that has already been installed on your system.

If any changes have been made to the package while it was unpacked (e.g.
conffiles files in /etc modified), the new package will inherit the
changes. (There are exceptions to this, including changes to configuration
files that are not conffiles, including those managed by ucf.)

This utility can make it easy to copy packages from one computer
to another, or to recreate packages that are installed on your
system, but no longer available elsewhere.

Note:
.B dpkg\-repack
will place the created package in the current directory.
.
.SH OPTIONS
.TP
.BI \-\-root= dir
Take package from filesystem rooted on \fIdir\fP. This is useful if, for
example, you have another computer nfs mounted on /mnt, then you can use
\fB\-\-root=/mnt\fP to reassemble packages from that computer.
.
.TP
.BI \-\-arch= architecture
Make the package be for a specific \fIarchitecture\fP.
.B dpkg\-repack
might not be able to tell if an installed package is architecture \fBall\fP
or is specific to the system's architecture, in case it lacks the
.B Architecture
field. If you know the package architecture, you can use this option to force
.B dpkg\-repack
to use the right architecture.
.
.TP
.BR \-d ", " \-\-deb\-option "=\fIoption\fP"
Pass \fIoption\fP as build argument to \fBdpkg\-deb\fP.
This option can be specified multiple times.
.
.TP
.B \-\-generate
Generate a temporary directory suitable for building a package from, but do
not actually create the package. This is useful if you want to move files
around in the package before building it. The package can be built from
this temporary directory by running
"\fBdpkg\-deb \-\-build\fP \fIdir\fP \fB.\fP" as root (or by using
\fBfakeroot \-u\fP), where \fIdir\fP is the generated directory.
.
.TP
.BR \-\-tag "=\fIthing\fP[,...]"
Specify a comma-separated list of things to tag in the package as having
been repackaged.
The current list of \fIthing\fPs to tag is:
.RS
.TP
.B none
Tag nothing.
This can be specified first to be augmented by more specific \fIthing\fPs.
.TP
.B description
Append a timestamped "Repackaged by dpkg-repack" tagline to the package's
control file \fBDescription\fP field.
This tag is enabled by default.
.TP
.B version
Append a "+repack" tag to the package version.
.TP
.B all
Tag everything.
.RE
.
.TP
.I package-name
The name of the package to attempt to repack. Multiple packages can be listed.
.
.SH BUGS
There is a tricky situation that can occur if you \fBdpkg\-repack\fP a package
that has modified conffiles. The modified conffiles are packed up. Now if
you install the package, \fBdpkg\fP(1) does not realize that the conffiles
in it are modified. So if you later upgrade to a new version of the package,
\fBdpkg\fP(1) will believe that the old (repacked) package has older conffiles
than the new version, and will silently replace the conffiles with those in
the package you are upgrading to.
.P
While \fBdpkg\-repack\fP can be run under \fBfakeroot\fP(1) and will work
most of the time, \fBfakeroot \-u\fP must be used if any of the files to be
repacked are owned by non-root users. Otherwise the package will have them
owned by root.
\fBdpkg\-repack\fP will warn if you run it under \fBfakeroot\fP(1) without
the \fB\-u\fP flag.
.
.SH SEE ALSO
.BR dpkg (1),
.BR dpkg-deb (1),
.BR fakeroot (1).
.
.SH AUTHOR
Joey Hess <joeyh@debian.org>
