.TH DPKG-REPACK 1L "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
dpkg-repack \- Utility to put an unpacked .deb file back together
.SH SYNOPSIS
\fBdpkg-repack\fP [\fBpackage\fP]
.br
.SH DESCRIPTION
.I dpkg-repack
tries to create a .deb file out of a debian package 
that has already been installed on your system. If any changes have 
been made to the package while it was unpacked (ie, files in /etc 
modified), the new package will inherit the changes.

This utility can make it easy to copy packages from one computer 
to another, or to recreate packages that are installed on your 
system, but no longer available elsewhere.

.SS BUGS

There will certainly be cases where this program fails to work.
Please report them to the author of dpkg-repack.

Be warned that the author has only a shallow understanding of the 
dpkg packaging system, so there are probably tons of bugs in this
program. Also, this program is experimental code. Use at your own 
risk!

.SS AUTHOR
Joey Hess <joeyh@master.debian.org>
