#!/bin/sh

set -e
set -u

cmp_ctrlfile()
{
  local pkg=$1
  local ctrl=$2

  dpkg-query --control-show $pkg $ctrl >$pkg-inst.$ctrl
  dpkg-deb --info ${pkg}_*.deb $ctrl >$pkg-pack.$ctrl
  diff -u $pkg-inst.$ctrl $pkg-pack.$ctrl
}

cmp_listfile()
{
  local pkg=$1

  dpkg-query --listfiles $pkg | sort >$pkg-inst.list
  dpkg-deb --fsys-tarfile ${pkg}_*.deb | tar -tf - | cut -c2- \
    | sed -e 's,^/$,/.,;s,/$,,g' | sort >$pkg-pack.list
  diff -u $pkg-inst.list $pkg-pack.list
}

test_pkgs="dpkg dpkg-repack"

cd $AUTOPKGTEST_TMP
fakeroot -u dpkg-repack $test_pkgs

for pkg in $test_pkgs; do
  for ctrl in $(dpkg-query --control-list $pkg); do
    cmp_ctrlfile $pkg $ctrl
  done
  cmp_listfile $pkg
done

cmp_ctrlfile dpkg conffiles

# FIXME: check control file
# FIXME: check diverted files
# FIXME: check obsolete conffiles
# FIXME: check --generate
# FIXME: check --arch
# FIXME: check --deb-option
# FIXME: check --root
